name: Build Test

on:
  push:
    branches: [dev]

jobs:
  build:
    name: build test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: build
        run: yarn build